Update lexicon.js
mr-martian/Sajem_Tan pull request #5
Opened 2020-02-10 03:16 UTC by Cyfek

Update to lexicon (first part, will do the rest tomorrow)

2020-02-10 03:20 UTC, mr-martian commented
"zisnam" is missing a closing bracket. There's a handful of consistency things in the glosses, but I'll fix them myself later. (apologies for my complete absence of late)

2020-02-10 03:35 UTC, Cyfek commented
Oh, no problem. I'm so sure how to fix things like that, so if you could commit it whenever, then fix it, that'd be great

2020-02-18 21:03 UTC, Cyfek commented
@mr-martian hey, it's done

2020-02-18 21:48 UTC, mr-martian requested changes

2020-02-18 21:48 UTC, mr-martian commented on lexicon.js
> +    "kek": ["supplemental", "more],
missing close quote

2020-02-20 15:19 UTC, merged